Transform: AWS::Serverless-2016-10-31
Resources:
  LastVisitedTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
  SkillHandler:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-SkillHandler
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: SkillHandler
      CodeUri: src/SkillHandler
      Handler: index.handler
      Runtime: nodejs14.x
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
        - DynamoDBCrudPolicy:
            TableName: !Ref LastVisitedTable
      Environment:
        Variables:
          TABLE_NAME: !Ref LastVisitedTable
          TABLE_ARN: !GetAtt LastVisitedTable.Arn
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill
          Properties:
            SkillId: !Ref HeyYinzID
Parameters:
  HeyYinzID:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /staging/hey-yinz-id
